<?php

function asset_image_default_asset_type() {
  $items = array();
  $items['image'] = entity_import('asset_type', '{
    "type" : "image",
    "name" : "Image",
    "icon" : "AddImage.png",
    "description" : "Sample Image",
    "help" : "",
    "weight" : "0",
    "locked" : "0",
    "rdf_mapping" : []
  }');
  return $items;
}


/**
 * Implements hook_image_default_styles().
 */
function asset_image_image_default_styles() {
  $styles = array();

  // Exported image style: asset_image_full.
  $styles['asset_image_full'] = array(
    'name' => 'asset_image_full',
    'effects' => array(
      2 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => '640',
          'height' => '360',
        ),
        'weight' => '1',
      ),
    ),
  );

  // Exported image style: asset_image_small.
  $styles['asset_image_small'] = array(
    'name' => 'asset_image_small',
    'effects' => array(
      1 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => '320',
          'height' => '180',
        ),
        'weight' => '1',
      ),
    ),
  );

  return $styles;
}
