<?php
// $Id$

define('ASSET_PRIVATE',0);
define('ASSET_PUBLIC',1);

function asset_bonus_menu($may_cache){
  if(!$may_cache){
    $items[] = array(
      'path' => 'admin/settings/asset/asset_bonus',
      'title' => t('Asset Bonus'),
      'access' => user_access('administer assets'),
      'callback' => 'asset_bonus_admin_overview',
      'type' => MENU_LOCAL_TASK,
      'weight' => 1,
    );
    $items[] = array(
      'path' => 'admin/settings/asset/asset_bonus/overview',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'title' => t('Overview'),
      'weight' => -10,
      'access' => user_access('administer assets'),
      'callback' => 'asset_bonus_admin_overview',
    );
    $items[] = array(
      'path' => 'admin/settings/asset/asset_bonus/mp3player',
      'type' => MENU_LOCAL_TASK,
      'title' => t('mp3 Player'),
      'access' => user_access('administer assets'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('asset_bonus_admin_mp3player'),
    );

  }
  return $items;
}

function asset_bonus_admin_overview(){
  if(!file_exists(drupal_get_path('module','asset_bonus').'/swfobject/swfobject.js')){
    $output .= '<p>Asset Bonus Pack requires the download of an additional set of files '
            . ' available <a href="http://digett.com/asset_bonus.zip">here</a>.</p>';
  }else{
    $output .= '<p>Asset Bonus Pack has been successfully configured.</p>';
  }
  return $output;
}

function asset_bonus_mp3player_colors(){
  return array(
    'bg' => t('Background'),
    'leftbg' => t('Left Background'),
    'lefticon' => t('Left Icon'),
    'rightbg' => t('Right Background'),
    'rightbghover' => t('Right Background Hover'),
    'righticon' => t('Right Icon'),
    'righticonhover' => t('Right Icon Hover'),
    'text' => t('Text'),
    'slider' => t('Slider'),
    'track' => t('Track'),
    'border' => t('Border'),
    'loader' => t('Loader'),
  );
}
  
function asset_bonus_admin_mp3player(){
  // Add Farbtastic color picker
  drupal_add_css('misc/farbtastic/farbtastic.css', 'module', 'all', FALSE);
  drupal_add_js('misc/farbtastic/farbtastic.js');
  drupal_add_js(array('asset_bonus_path' => drupal_get_path('module','asset_bonus')),'setting');

  drupal_add_css(drupal_get_path('module','asset_bonus').'/asset_bonus.css');
  drupal_add_js(drupal_get_path('module','asset_bonus').'/asset_bonus.js');
  
  $colors = asset_bonus_mp3player_colors();
  $form['palette'] = array(
    '#type' => 'fieldset',
    '#title' => t('Color Palette'),
    '#attributes' => array('id'=>'palette'),
    );
  foreach($colors as $key=>$title){
    $form['palette']['asset_bonus_mp3player_'.$key] = array(
      '#type' => 'textfield',
      '#title' => $title,
      '#default_value' => variable_get('asset_bonus_mp3player_'.$key,''),
      '#size' => 8,
    );
  }
  $form[] = array('#value' => '<div id="color-map">'.theme('image',drupal_get_path('module','asset_bonus').'/audioplayer/map.gif').'</div>');
  $form[] = array('#value' => '<div>Audio Player by:<br/>'.l(theme('image',drupal_get_path('module','asset_bonus').'/audioplayer/logo.gif'),'http://www.1pixelout.net/code/audio-player-wordpress-plugin/',array(),null,null,false,true).'</div>');
  return system_settings_form($form);
}

function asset_bonus_asset_formatter($op='list',$asset=null,$attr=array()){
  switch($op){          
    case 'info':
      $formats['mp3player'] = array(
        'name' => 'mp3 Player',
        'types' => array('local' => array('mp3')),
        'description' => t('Embed the mp3 file using the !1pixelout audio player',
          array('!1pixelout'=>l('1pixelout','http://www.1pixelout.net/code/audio-player-wordpress-plugin/'))),
      );
      $formats['swfobject'] = array(
        'name' => 'swfobject',
        'types' => array('local' => array('swf')),
        'description' => t('Embed the flash movie using the !swfobject javascript library',
          array('!swfobject'=>l('swfobject','http://blog.deconcept.com/swfobject/'))),
      );
      // @NOTE: the formatter info array is cached which causes problems here
      if (_asset_is_id3()) {
        $formats['id3'] = array(
          'name' => 'id3',
          'types' => array('local' => array( // @TODO: what are these?
            /*aud*/ 'mp3', 'wav', 'aac', 'ram',
            /*vid*/ 'avi', 'mov', 'wmv', 'mpeg', 'mp4', 'mpeg2', 'dv', 'swf',
            /*img*/ 'bmp', 'gif', 'jpg', 'png')),
          'description' => t('Display the getid3 Audio/Video information'),
        );
      }
      return $formats;
    case 'init':
      drupal_add_js(drupal_get_path('module','asset_bonus').'/swfobject/swfobject.js');
      drupal_add_js(drupal_get_path('module','asset_bonus').'/audioplayer/audio-player.js');
      break;      
    case 'options':
    case 'preview':
    case 'details':
    case 'img':
      $function = 'asset_bonus_'.$attr['format'].'_'.$op;
      if(function_exists($function)){
        return call_user_func($function,$asset);
      }
      break;
    case 'render':
      $function = 'asset_bonus_'.$attr['format'];
      return theme($function,$asset,$attr);
  }
}

function asset_bonus_swfobject_options($asset){
  require_once(drupal_get_path('module','asset_bonus').'/swfheader/swfheader.class.php');
  $swf = new swfheader();
  $swf->getDimensions($asset->filepath);
  $form['width'] = array(
    '#type' => 'textfield',
    '#title' => t('Width'),
    '#description' => t('Width in pixels'),
    '#default_value' => $swf->width,
    '#size' => 5,
    '#required' => true,
  );
  $form['height'] = array(
    '#type' => 'textfield',
    '#title' => t('Height'),
    '#description' => t('Height in pixels'),
    '#default_value' => $swf->height,
    '#size' => 5,
    '#required' => true,
  );
  $form['version'] = array(
    '#type' => 'textfield',
    '#title' => t('Minimum Version'),
    '#default_value' => $swf->version, 
    '#size' => 5,
    '#required' => true,
  );
  $form['bgcolor'] = array(
    '#type' => 'textfield',
    '#title' => t('Background Color'),
    '#description' => t('Hex formatted background color like #FFFFFF. Make sure to include the #.'),
    '#default_value' => '#FFFFFF',
    '#size' => 7,
    '#required' => true,
  );

  // add the id3 options
  if (isset($asset->id3)) {
    $form = array_merge($form, asset_bonus_id3_options_form());
  }

  return $form;
}

function asset_bonus_swfobject_preview($asset){
  require_once(drupal_get_path('module','asset_bonus').'/swfheader/swfheader.class.php');
  $swf = new swfheader();
  list($w,$h) = explode('|',$swf->getDimensions($asset->filepath));
  $r = ($w > $h) ? ($w / 150) : ($h / 150);
  $attr = array('height'=>($h/$r),'width'=>($w/$r),'version'=>$swf->version,'bgcolor'=>'#FFFFFF');
  $output = theme('asset_bonus_swfobject',$asset,$attr);
  return $output;
}

function asset_bonus_swfobject_details($asset){
  require_once(drupal_get_path('module','asset_bonus').'/swfheader/swfheader.class.php');
  $swf = new swfheader();
  $swf->getDimensions($asset->filepath);
  
  $details = array(
    t('Width') => $swf->width.'px',
    t('Height') => $swf->height.'px',
    t('Flash Version') => $swf->version,
    t('Compressed') => ($swf->compressed ? t('Yes') : t('No')),
    t('FPS') => $swf->fps[1],
    t('Frames') => $swf->frames,
  );
  
  return $details;
}

function theme_asset_bonus_swfobject($asset, $options=array()){
  $embed_id = 'embed-'.preg_replace('/[^A-Za-z_-]/','-',substr($asset->filename,0,strlen($asset->filename)-4));
  $div_id = 'swfobject-'.preg_replace('/[^A-Za-z_-]/','-',substr($asset->filename,0,strlen($asset->filename)-4));
  $embed_id = 'swfobject-object-'.$asset->aid;
  $div_id = 'swfobject-'.$asset->aid;
  
  // build a list of addVariable statements for each flashVar
  $addVariable = '';
  foreach((array)$options['vars'] as $k=>$v){
    $addVariable .= "oSwf.addVariable('$k','$v');\n";
  }
  // build a list of addParam statements for known params
  if($options['transparent']){
    $addParam .= "oSwf.addParam('wmode','transparent');\n";
  }
  
  $output = <<<OUT
  <div id="$div_id" class="asset-swfobject">Replacement Text</div>
  <script type="text/javascript">
    var oSwf = new SWFObject("{$asset->url}","$embed_id","{$options['width']}","{$options['height']}","{$options['version']}","{$options['bgcolor']}");
    $addVariable
    $addParam
    oSwf.write("$div_id");
    oSwf = null;
  </script>      
OUT;

  // add the id3 options
  if (isset($asset->id3)) {
    $output .= theme('asset_bonus_id3', $asset, $options);
  }

  return $output;
}

function asset_bonus_mp3player_options($asset){
  $form['width'] = array('#type' => 'hidden', '#value' => '290');
  $form['height'] = array('#type' => 'hidden', '#value' => '24');

  // add the id3 options
  if (isset($asset->id3)) {
    $form = array_merge($form, asset_bonus_id3_options_form());
  }

  return $form;
}

function asset_bonus_mp3player_preview($asset){
  return theme('asset_bonus_mp3player',$asset,$attr);
}

function asset_bonus_mp3player_img($asset){
  return drupal_get_path('module','asset_bonus').'/audioplayer.png';
}

function theme_asset_bonus_mp3player($asset, $options=array()){
  global $base_url;
  $swffile = $base_url .'/'. drupal_get_path('module', 'asset_bonus') .'/audioplayer/player.swf';
  $colors = asset_bonus_mp3player_colors();
  foreach($colors as $key => $title){
    $color = variable_get('asset_bonus_mp3player_'.$key,'');
    if($color){
      $color = str_replace('#','0x',$color);
      $colorvars .= "oSwf.addVariable('$key','$color');";
    }
  }
  $output = <<<OUT
  <div id="mp3player-{$asset->aid}" class="asset-swfobject">Replacement Text</div>
  <script type="text/javascript">
    var oSwf = new SWFObject("$swffile","mp3player-object-{$asset->aid}","290","24","7","#FFFFFF");    
    oSwf.addVariable('playerID','{$asset->aid}');
    oSwf.addVariable('soundFile','{$asset->url}');
    $colorvars
    oSwf.addParam('wmode','transparent');
    oSwf.addParam('menu','false');
    oSwf.write("mp3player-{$asset->aid}");
    oSwf = null;
  </script>      
OUT;

  // add the id3 options
  if (isset($asset->id3)) {
    $output .= theme('asset_bonus_id3', $asset, $options);
  }

  return $output;
}

function asset_bonus_id3_options($asset) {
  // don't display the width/height/or alignment
  $form['width'] = array('#type' => 'hidden', '#value' => 0);
  $form['height'] = array('#type' => 'hidden', '#value' => 0);
  $form['align'] = array('#type' => 'hidden', '#value' => 'none');

  // add the id3 options
  if (isset($asset->id3)) {
    $form = array_merge($form, asset_bonus_id3_options_form());
  }

  return $form;
}

function asset_bonus_id3_options_form() {
  // give the user some control over the display
  $form['id3_playtime'] = array(
    '#type' => 'checkbox',
    '#title' => t('Playtime'),
    '#default_value' => TRUE,
  );
  $form['id3_tags'] = array(
    '#type' => 'checkbox',
    '#title' => t('Tags'),
    '#default_value' => TRUE,
  );
  $form['id3_tech'] = array(
    '#type' => 'checkbox',
    '#title' => t('Technical Details'),
  );
  if (user_access('administer assets')) {
    $form['id3_all'] = array(
      '#type' => 'checkbox',
      '#title' => t('Everything (Mostly for Debugging)'),
    );
  }
  return $form;
}

function asset_bonus_id3_preview($asset) {
  return theme('asset_bonus_id3', $asset);
}

function theme_asset_bonus_id3($asset, $options = array()) {
  $header = array(t('Name'), t('Value'));
  $rows = array();
  if ($options['id3_all']) {
    _asset_bonus_add_id3_rows($asset->id3, $rows);
  }
  else {
    // add the playtime string
    if ($options['id3_playtime']) {
      $rows[] = array(t('Playtime'), $asset->id3['playtime_string']);
    }

    // add the id3 tags
    if ($options['id3_tags']) {
      // store the tag values in a temporary array, letting higher numbered
      // id3 version tags override lower number version tags
      $tags = array();
      foreach ($asset->id3['tags'] as $id3v) {
        foreach ($id3v as $tag => $value) {
          $tags[$tag] = $value[0];
        }
      }

      // remove id3v1 tags that exist in id3v2 with a slightly different name
      if (isset($tags['comments'])) {
        unset($tags['comments']);
      }
      if (isset($tags['track_number'])) {
        unset($tags['track']);
      }

      // now add all of the tags to the output array
      foreach ($tags as $tag => $value) {
        $rows[] = array($tag, $value);
      }
    }

    // add the technical information
    if ($options['id3_tech']) {
      $rows[] = array('filesize', $asset->id3['filesize']);
      $rows[] = array('fileformat', $asset->id3['fileformat']);

      if (isset($asset->id3['audio'])) {
        $options = array(
          '%channels' => $asset->id3['audio']['channels'],
          '%channelmode' => $asset->id3['audio']['channelmode'],
          '%sample_rate' => $asset->id3['audio']['sample_rate'],
          '%bitrate' => $asset->id3['audio']['bitrate']
        );
        $value = t('%channels %channelmode channels %sample_rate samplerate %bitrate bitrate', $options);
        $rows[] = array('audio', $value);
      }
    }
  }
  return theme('asset_bonus_id3_table', $header, $rows);
}

function theme_asset_bonus_id3_table($header, $rows) {
  if (count($rows) > 0) {
    return theme('table', $header, $rows);
  }
}

function _asset_bonus_add_id3_rows($a, &$rows, $prefix = '') {
  foreach ($a as $key => $value) {
    if (is_array($value)) {
      _asset_bonus_add_id3_rows($value, $rows, $prefix . $key .'.');
    }
    else {
      $rows[] = array($prefix . $key, $value);
    }
  }
}

function _asset_is_id3($require = FALSE) {
  $lib = 'misc/lib/getid3/getid3/getid3.php';
  if (file_exists($lib)) {
    if ($require) {
      require_once($lib);
    }
    return 1;
  }
}

function asset_bonus_assetapi($op, $asset) {
  switch ($op) {
    case 'load':
      if ($data = db_result(db_query("SELECT data FROM {asset_bonus} WHERE aid=%d", $asset->aid))) {
        return array('id3' => unserialize($data));
      }
      break;

    case 'insert':
      if ($asset->status) {
        if ($path = realpath(file_directory_path() .'/'. $asset->filepath)) {
          if (_asset_is_id3(TRUE)) {
            $id3 = new getID3();
            $id3->option_md5_data = true;
            $id3->option_md5_data_source = true;
            $id3->encoding = 'UTF-8';
            $info = $id3->analyze($path);
            if (isset($info['id3v2']['APIC'])) {
              // @TODO: save the picture, but don't store in the database
              unset($info['id3v2']['APIC']);
            }
            db_query("INSERT INTO {asset_bonus} (aid, data) VALUES (%d, '%s')", $asset->aid, serialize($info));
          }
        }
      }
      break;

    // NOTE: not implemented yet
    case 'update':
      break;
    case 'delete':
      break;
  }    
}
